version: "3"

services:

  back:
    image: share-space-back
    container_name: share-space-back
    build: ./back
    restart: always
    volumes:
      - ./back/app:/app
      - /app/node_modules
      - /app/build
    networks:
      - backend

  front:
    image: share-space-front
    container_name: share-space-front
    build: ./front
    volumes:
      - ./front/app:/app
      - /app/node_modules

  nginx:
    image: nginx:stable
    container_name: share-space-nginx
    restart: always
    volumes:
      - ./front/app:/web
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    ports:
      - 80:80

  mysql:
    image: share-space-mysql
    container_name: share-space-mysql
    build: ./mysql
    restart: always
    volumes:
      - ./mysql/volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=[PASSWORD]

networks:

  backend:
